version: '3.0'
services:
  rasa:
    container_name: rasa
    image: rasa/rasa:1.10.3-full
    restart: always
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command: run --enable-api

  app:
    container_name: common
    volumes:
      - ./common:/app/common
    restart: always
    image: wireless911/rasa-demo:1.5
#    ports:
#      - 5055:5055
    expose:
      - 5055
networks:
  default:
    external:
      name: rasa_default